"use client";

import {
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Ban,
  Bell,
  BellRing,
  Building,
  Building2,
  Calculator,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleX,
  Columns3,
  Copy,
  CreditCard,
  Download,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FileUp,
  Globe,
  Grid3X3,
  GripVertical,
  Heart,
  Image,
  ImagePlus,
  Info,
  LayoutDashboard,
  List,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  Menu,
  MessageCircle,
  MinusCircle,
  Package,
  PanelLeftOpen,
  Pencil,
  PlayCircle,
  Plus,
  PlusCircle,
  Quote,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Rocket,
  Search,
  SearchX,
  Send,
  ShieldCheck,
  ShoppingCart,
  SlidersHorizontal,
  Star,
  Store,
  Table2,
  Tag,
  ToggleRight,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Upload,
  UserRound,
  Users,
  UtensilsCrossed,
  Warehouse,
  WifiOff,
  X,
} from "lucide-react";
import type { ComponentProps } from "react";

const ICON_MAP: Record<string, LucideIcon> = {
  add: Plus,
  add_circle_outline: PlusCircle,
  add_photo_alternate: ImagePlus,
  add_shopping_cart: ShoppingCart,
  admin_panel_settings: ShieldCheck,
  arrow_back: ArrowLeft,
  arrow_drop_down: ChevronDown,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  block: Ban,
  business: Building,
  calculate: Calculator,
  calendar_today: Calendar,
  cancel: CircleX,
  chat: MessageCircle,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  category: Grid3X3,
  contacts: UserRound,
  close: X,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_outline: Trash2,
  description: FileText,
  content_copy: Copy,
  credit_card: CreditCard,
  download: Download,
  drag_indicator: GripVertical,
  more_horiz: Ellipsis,
  edit: Pencil,
  error_outline: CircleAlert,
  favorite: Heart,
  format_quote: Quote,
  grid_view: Grid3X3,
  image: Image,
  info: Info,
  info_outline: Info,
  inventory: Package,
  inventory_2: Package,
  language: Globe,
  local_shipping: Truck,
  local_offer: Tag,
  location_city: Building2,
  location_on: MapPin,
  lock: Lock,
  lock_outline: Lock,
  login: LogIn,
  logout: LogOut,
  mail: Mail,
  mail_outline: Mail,
  map: Map,
  menu: Menu,
  menu_open: PanelLeftOpen,
  my_location: MapPin,
  notifications_active: BellRing,
  notifications_none: Bell,
  open_in_new: ExternalLink,
  person: UserRound,
  person_search: UserRound,
  point_of_sale: ReceiptText,
  person_outline: UserRound,
  place: MapPin,
  play_circle: PlayCircle,
  payments: ReceiptText,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  rotate_ccw: RotateCcw,
  remove_circle_outline: MinusCircle,
  remove_shopping_cart: ShoppingCart,
  restaurant_menu: UtensilsCrossed,
  rocket_launch: Rocket,
  search: Search,
  search_off: SearchX,
  sell: Tag,
  send: Send,
  settings: SlidersHorizontal,
  shopping_cart: ShoppingCart,
  star: Star,
  store: Store,
  storefront: Store,
  swap_horiz: ArrowLeftRight,
  table_chart: Table2,
  tag: Tag,
  task_alt: CircleCheck,
  toggle_on: ToggleRight,
  trending_up: TrendingUp,
  trending_down: ArrowDown,
  tune: SlidersHorizontal,
  unfold_more: ArrowUpDown,
  upload: Upload,
  upload_file: FileUp,
  visibility: Eye,
  visibility_off: EyeOff,
  hourglass_empty: Loader2,
  group: Users,
  view_column: Columns3,
  view_list: List,
  warehouse: Warehouse,
  warning: TriangleAlert,
  warning_amber: TriangleAlert,
  wifi_off: WifiOff,
};

type IconProps = {
  name: string;
  className?: string;
} & Omit<ComponentProps<"svg">, "name">;

export function Icon({ name, className, ...props }: IconProps) {
  const Lucide = ICON_MAP[name] ?? CircleAlert;
  return (
    <Lucide
      className={`material-icons ${className ?? ""}`.trim()}
      width="1em"
      height="1em"
      strokeWidth={2}
      aria-hidden
      {...props}
    />
  );
}
